a = int(input("Enter the number: "))
b = int(input("Enter the number: "))

print("sum:",a + b)
print("difference:",a - b)
print("product:",a * b)
print("division:",a / b)
print("floor:",a // b)
print("remainder:",a % b)
print("power:",a ** b)
print("a equal b:",a == b)
print("a not equal b:",a != b)
print("a greater than b:", a > b)
print("a less than b:",a < b)
print("a greater or equal b:", a >= b)
print("a less or equal b:", a <= b)

print("a>5 and b<10 true if both true:",a>5 and b<10)
print("a>5 or b>10 true if at least one true:",a>5 or b>10)
print("not(a>5) negates truth value:",not(a>5))